# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [push]
env: MAME_SUBTARGET=tiny

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  mingw-windows-build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: setup environment
      run: |
        sudo apt-get install mingw-w64
        sudo update-alternatives --set x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-posix
    - name: build w64
      run: make -j$(nproc) OPTIMIZE=3 TOOLS=1 SUBTARGET=$MAME_SUBTARGET TARGETOS=windows PTR64=1 OVERRIDE_CC=x86_64-w64-mingw32-gcc OVERRIDE_CXX=x86_64-w64-mingw32-g++ OVERRIDE_LD=x86_64-w64-mingw32-ld MINGW64=/usr
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: binaries
        path: ./*.exe
  msys-windows-build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: bash git make wget
    - uses: actions/checkout@v2
