# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  mingw-windows-build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Setup environment
      run: |
        sudo apt update
        sudo apt-get install mingw-w64 wine64 p7zip
        sudo update-alternatives --set x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-posix
    - name: build w64
      run: make -j$(nproc) OPTIMIZE=3 TOOLS=1 SUBTARGET=tiny TARGETOS=windows PTR64=1 OVERRIDE_CC=x86_64-w64-mingw32-gcc OVERRIDE_CXX=x86_64-w64-mingw32-g++ OVERRIDE_LD=x86_64-w64-mingw32-ld MINGW64=/usr
    - name: Create MAME basic configuration
      run: wine64 mametiny64.exe -createconfig
    - name: Create Release Asset
      run: 7z a groovymame-mingw-win32-64bits.7z *.exe COPYING mame.ini uismall.bdf artwork/ bgfx/ ctrlr/ docs/ hash/ hlsl/ ini/ language/ plugins/ roms/ samples/ -x!./pngcmp.exe -x!./regrep.exe -x!./split.exe -x!./srcclean.exe
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: binaries-win32-mingw
        path: groovymame-mingw-win32-64bits.7z
  msys-windows-build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: bash git make wget mingw-w64-x86_64-gcc mingw-w64-x86_64-python p7zip
    - shell: msys2 {0}
      run: |
        wget https://repo.mamedev.org/x86_64/mame-essentials-1.0.6-1-x86_64.pkg.tar.xz
        pacman -U --noconfirm mame-essentials-1.0.6-1-x86_64.pkg.tar.xz
        echo -e "[mame]\nInclude = /etc/pacman.d/mirrorlist.mame" >> /etc/pacman.conf
        pacman -Sy
    - uses: actions/checkout@v2
    - shell: msys2 {0}
      run: |
        export MINGW64=/mingw64
        export MINGW32=
        make -j$(nproc) OPTIMIZE=3 TOOLS=1 SUBTARGET=tiny
    - shell: msys2 {0}
      run: mametiny64.exe -createconfig
    - shell: msys2 {0}
      run: run: 7z a groovymame-msys-win32-64bits.7z *.exe COPYING mame.ini uismall.bdf artwork/ bgfx/ ctrlr/ docs/ hash/ hlsl/ ini/ language/ plugins/ roms/ samples/ -x!./pngcmp.exe -x!./regrep.exe -x!./split.exe -x!./srcclean.exe
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: binaries-win32-msys
        path: groovymame-msys-win32-64bits.7z
  release:
    needs: [mingw-windows-build, msys-windows-build]
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release $GITHUB_SHA
          draft: false
          prerelease: false
